from .usuarioserializer import UsuarioSerializer
from .familiarserializer import FamiliarSerializer
from .histclinicaserializer import HistoriaClinicaSeralizer
from .pacienteserializer import PacienteSerializer
from .Psaludserializer import PersonalSaludSerializer
from .sigvitalesserializer import SignosVitalesSerializer