# Generated by Django 4.1.1 on 2022-09-07 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('authApp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signos_vitales',
            fields=[
                ('id_sigvitales', models.AutoField(primary_key=True, serialize=False)),
                ('oximetria', models.IntegerField(default=0)),
                ('frecuencia_card', models.IntegerField(default=0)),
                ('frecuencia_resp', models.IntegerField(default=0)),
                ('temperatura', models.IntegerField(default=0)),
                ('glicemias', models.IntegerField(default=0)),
                ('presion_art', models.IntegerField(default=0)),
                ('fecha_registro', models.DateTimeField()),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sig_vitales', to='authApp.paciente')),
            ],
        ),
        migrations.CreateModel(
            name='Historia_clinica',
            fields=[
                ('id_histClinica', models.AutoField(primary_key=True, serialize=False)),
                ('sugerencias', models.CharField(max_length=250, verbose_name='Sugerencias')),
                ('diagnostico', models.CharField(max_length=250, verbose_name='Diagnostico')),
                ('entorno', models.CharField(max_length=250, verbose_name='Entorno')),
                ('fecha_sugerencia', models.DateField()),
                ('descipcion', models.CharField(max_length=250, verbose_name='Descripcion')),
                ('id_paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hist_clinica', to='authApp.paciente')),
            ],
        ),
    ]
