from .Usuarioview import CrearUsuarioView
from .Usuarioview import UsuarioView
from .Psaludview import PersonalSaludView
from .Psaludview import CrearPersonalSaludView
from .familiarview import CrearFamiliarView
from .familiarview import FamiliarView
from .Hist_clinicaview import CrearHistoriaClinicaView
from .Hist_clinicaview import HistoriaClinicaView
from .pacienteview import CrearPacienteView
from .pacienteview import PacienteView
from .Sig_vitalesview import CrearSignosVitalesView
from .Sig_vitalesview import SignosVitalesView